export const data = [
    {
        id: 1,
        title: "comment faire pour devenir un developpeur web",
        description: "je suis un etudiant en informatique et je suis interessé par le developpement web, mais je ne sais pas par ou commencer",
        date: "2024-10-23",
        auteur: "John Doe",
        image: "https://via.placeholder.com/150",
        reponse: 0,
        reaction:15,
    },
    {
        id: 2,
        title: "Les meilleures pratiques en cybersécurité",
        description: "Quelles sont les meilleures pratiques actuelles pour assurer la sécurité des systèmes informatiques d'une entreprise ?",
        date: "2024-11-05",
        auteur: "Alice Martin",
        reponse: 0,
        reaction:15,
    },
    {
        id: 3,
        title: "Intelligence artificielle : opportunités et défis",
        description: "Discutons des opportunités et des défis éthiques liés à l'adoption croissante de l'IA dans divers secteurs.",
        date: "2024-11-15",
        auteur: "Pierre Dupont",
        image: "https://via.placeholder.com/150",
        reponse: 0,
        reaction:15,
    },
    {
        id: 4,
        title: "Optimisation des performances des applications mobiles",
        description: "Quelles sont vos astuces pour améliorer les performances des applications mobiles sur iOS et Android ?",
        date: "2024-12-01",
        auteur: "Sophie Lefebvre",
        image: "https://via.placeholder.com/150",
        reponse: 0,
        reaction:15,
    },
    {
        id: 5,
        title: "L'avenir du cloud computing",
        description: "Comment voyez-vous l'évolution du cloud computing dans les prochaines années ? Quelles technologies vont émerger ?",
        date: "2024-12-10",
        auteur: "Marc Tremblay",
        image: "https://via.placeholder.com/150",
        reponse: 0,
        reaction:15,
    },
    {
        id: 6,
        title: "Débat : Framework vs Vanilla JavaScript",
        description: "Faut-il toujours utiliser un framework JavaScript ou y a-t-il des cas où le JavaScript vanilla est préférable ?",
        date: "2024-12-20",
        auteur: "Emma Dubois",
        image: "https://via.placeholder.com/150",
        reponse: 0,
        reaction:15,
    }
]